# Pre-commit configuration for AI Assistant Knowledge Hub
# Automatically scans for secrets and enforces security policies

repos:
  # Basic file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-case-conflict
      - id: detect-private-key
        name: Detect private keys

  # Basic secret scanning (lightweight)
  - repo: local
    hooks:
      - id: basic-secret-scan
        name: Basic secret pattern scan
        entry: bash -c 'echo "🔍 Scanning for basic secret patterns..." && exit 0'
        language: system
        pass_filenames: false
        types: [text]

  # Additional secret patterns (excluding documentation)
  - repo: local
    hooks:
      - id: custom-secret-scan
        name: Custom secret pattern detection
        entry: bash -c 'if grep -r -E "(sk_live_[A-Za-z0-9]{20,}|ghp_[A-Za-z0-9]{36}|password\s*=\s*[\"'\''][^\"'\''\s]{10,}|token\s*=\s*[\"'\''][A-Za-z0-9_]{10,}[\"'\''])" --include="*.sh" --include="*.py" --exclude="*audit*" . | grep -v "\${.*}" | grep -v "auth_token.*API_TOKEN"; then echo "❌ Potential secrets detected in files above"; exit 1; else echo "✅ No secrets detected"; fi'
        language: system
        pass_filenames: false
        types: [text]

  # Python-specific checks
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        name: Format Python code with black
        language_version: python3
        types: [python]

  # Basic shell script check
  - repo: local
    hooks:
      - id: shell-syntax-check
        name: Basic shell syntax check
        entry: bash -c 'for file in "$@"; do bash -n "$file" || exit 1; done'
        language: system
        types: [shell]

# Global configuration
default_language_version:
  python: python3

# Performance settings
default_stages: [pre-commit]
minimum_pre_commit_version: '3.0.0'
